### ISSUE TITLE
Keypress safety

### ISSUE THREAD

**Issue by cpaxton** [cpaxton/costar_stack#60]
```
Traceback (most recent call last):
  File "/home/chris/catkin_ws/src/costar_stack/costar_instructor/instructor_core/nodes/instructor_view.py", line 1490, in keyPressEvent
    elif 'root' in self.current_node_plugin_name.lower():
AttributeError: 'Instructor' object has no attribute 'current_node_plugin_name'
Traceback (most recent call last):
  File "/home/chris/catkin_ws/src/costar_stack/costar_instructor/instructor_core/nodes/instructor_view.py", line 1490, in keyPressEvent
    elif 'root' in self.current_node_plugin_name.lower():
AttributeError: 'Instructor' object has no attribute 'current_node_plugin_name'
```

**Comment by cpaxton** [comment]
in #61
